Sun May 31 04:53:51 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 12:53:56 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x56537327ccb0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x56537327ccb0 pid: 28801 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28801)
spawned uWSGI worker 1 (pid: 28802, cores: 1)
Internal Server Error: /addComment/Department
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 24, in addComment
    comment = models.Post()
AttributeError: module 'backendApi.models' has no attribute 'Post'
[pid: 28802|app: 0|req: 1/1] 122.238.122.231 () {42 vars in 1150 bytes} [Sun May 31 04:55:07 2020] GET /addComment/Department?%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB&Grade?17%E7%BA%A7&Identity?%E6%9C%AC%E7%A7%91%E7%94%9F&Name?%E5%BC%A0%E4%B8%89&Post?%E7%A5%9D%E7%A6%8F&phone?123 => generated 61586 bytes in 122 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
Not Found: /favicon.ico
[pid: 28802|app: 0|req: 2/2] 122.238.122.231 () {42 vars in 919 bytes} [Sun May 31 04:55:08 2020] GET /favicon.ico => generated 2598 bytes in 2 msecs (HTTP/1.1 404) 4 headers in 129 bytes (1 switches on core 0)
Internal Server Error: /addComment/Department
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 24, in addComment
    comment = models.Post()
AttributeError: module 'backendApi.models' has no attribute 'Post'
[pid: 28802|app: 0|req: 3/3] 122.238.122.231 () {44 vars in 1181 bytes} [Sun May 31 04:55:51 2020] GET /addComment/Department?%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB&Grade?17%E7%BA%A7&Identity?%E6%9C%AC%E7%A7%91%E7%94%9F&Name?%E5%BC%A0%E4%B8%89&Post?%E7%A5%9D%E7%A6%8F&phone?123 => generated 61723 bytes in 22 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
Sun May 31 04:56:00 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 12:56:02 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x55849c7b3cb0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55849c7b3cb0 pid: 28815 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28815)
spawned uWSGI worker 1 (pid: 28816, cores: 1)
Internal Server Error: /addComment/Department
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 24, in addComment
    comment = models.Post()
AttributeError: module 'backendApi.models' has no attribute 'Post'
[pid: 28816|app: 0|req: 1/1] 122.238.122.231 () {44 vars in 1181 bytes} [Sun May 31 04:56:03 2020] GET /addComment/Department?%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB&Grade?17%E7%BA%A7&Identity?%E6%9C%AC%E7%A7%91%E7%94%9F&Name?%E5%BC%A0%E4%B8%89&Post?%E7%A5%9D%E7%A6%8F&phone?123 => generated 61723 bytes in 137 msecs (HTTP/1.1 500) 5 headers in 156 bytes (1 switches on core 0)
Sun May 31 04:57:22 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 12:57:23 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x55bb4b70fcb0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55bb4b70fcb0 pid: 28847 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28847)
spawned uWSGI worker 1 (pid: 28848, cores: 1)
Internal Server Error: /addComment/Department
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 24, in addComment
    comment = models.Post()
AttributeError: module 'backendApi.models' has no attribute 'Post'
[pid: 28848|app: 0|req: 1/1] 122.238.122.231 () {44 vars in 1181 bytes} [Sun May 31 04:57:25 2020] GET /addComment/Department?%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB&Grade?17%E7%BA%A7&Identity?%E6%9C%AC%E7%A7%91%E7%94%9F&Name?%E5%BC%A0%E4%B8%89&Post?%E7%A5%9D%E7%A6%8F&phone?123 => generated 61723 bytes in 134 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
Sun May 31 04:57:54 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 12:57:56 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x55bcfc611cb0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55bcfc611cb0 pid: 28854 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28854)
spawned uWSGI worker 1 (pid: 28855, cores: 1)
Internal Server Error: /addComment/Department
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 24, in addComment
    comment = models.Post()
AttributeError: module 'backendApi.models' has no attribute 'Post'
[pid: 28855|app: 0|req: 1/1] 122.238.122.231 () {44 vars in 1181 bytes} [Sun May 31 04:57:58 2020] GET /addComment/Department?%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB&Grade?17%E7%BA%A7&Identity?%E6%9C%AC%E7%A7%91%E7%94%9F&Name?%E5%BC%A0%E4%B8%89&Post?%E7%A5%9D%E7%A6%8F&phone?123 => generated 61723 bytes in 135 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
Sun May 31 04:58:16 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
