Sun May 31 03:25:28 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 11:25:46 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x5601e84dbcd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x5601e84dbcd0 pid: 28357 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28357)
spawned uWSGI worker 1 (pid: 28358, cores: 1)
[pid: 28358|app: 0|req: 1/1] 122.238.122.231 () {44 vars in 1006 bytes} [Sun May 31 03:25:48 2020] GET /addComment/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB-17%E7%BA%A7-7%E7%8F%AD-%E5%BC%A0%E4%B8%89-%E7%A5%9D%E7%A6%8F-1234 => generated 26 bytes in 115 msecs (HTTP/1.1 200) 4 headers in 127 bytes (2 switches on core 0)
[pid: 28358|app: 0|req: 2/2] 122.238.122.231 () {42 vars in 977 bytes} [Sun May 31 03:25:54 2020] GET /addComment/%E8%AE%A1%E7%AE%97%E6%9C%BA%E7%B3%BB-17%E7%BA%A7-7%E7%8F%AD-%E5%BC%A0%E4%B8%89-%E7%A5%9D%E7%A6%8F-12345 => generated 29 bytes in 2049 msecs (HTTP/1.1 200) 4 headers in 127 bytes (2 switches on core 0)
Internal Server Error: /selectComment
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 60, in selectComment
    x = int(tmp[-1])
ValueError: invalid literal for int() with base 10: '/selectComment'
[pid: 28358|app: 0|req: 3/3] 122.238.122.231 () {44 vars in 859 bytes} [Sun May 31 03:26:00 2020] GET /selectComment => generated 59945 bytes in 28 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
Internal Server Error: /selectComment/1
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 60, in selectComment
    x = int(tmp[-1])
ValueError: invalid literal for int() with base 10: '/selectComment/1'
[pid: 28358|app: 0|req: 4/4] 122.238.122.231 () {42 vars in 839 bytes} [Sun May 31 03:26:02 2020] GET /selectComment/1 => generated 59849 bytes in 24 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
[pid: 28358|app: 0|req: 5/5] 122.238.122.231 () {42 vars in 839 bytes} [Sun May 31 03:26:07 2020] GET /selectComment-1 => generated 1556 bytes in 3 msecs (HTTP/1.1 200) 4 headers in 129 bytes (2 switches on core 0)
[pid: 28358|app: 0|req: 6/6] 122.238.122.231 () {42 vars in 833 bytes} [Sun May 31 03:26:33 2020] GET /like-1000000 => generated 27 bytes in 5 msecs (HTTP/1.1 200) 4 headers in 127 bytes (2 switches on core 0)
Internal Server Error: /lottery
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 113, in lottery
    res.append([data_top[x].UID, data_top[x].Name, data_top[x].Tag, data_top[x].Comment, data_top[x].Count, data_top[x].phone])
AttributeError: 'Comment' object has no attribute 'Tag'
[pid: 28358|app: 0|req: 7/7] 122.238.122.231 () {44 vars in 847 bytes} [Sun May 31 03:26:50 2020] GET /lottery => generated 60925 bytes in 24 msecs (HTTP/1.1 500) 5 headers in 156 bytes (2 switches on core 0)
Internal Server Error: /lottery
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./backendApi/views.py", line 113, in lottery
    res.append([data_top[x].UID, data_top[x].Name, data_top[x].Tag, data_top[x].Comment, data_top[x].Count, data_top[x].phone])
AttributeError: 'Comment' object has no attribute 'Tag'
[pid: 28358|app: 0|req: 8/8] 122.238.122.231 () {42 vars in 823 bytes} [Sun May 31 03:26:50 2020] GET /lottery => generated 60795 bytes in 36 msecs (HTTP/1.1 500) 5 headers in 156 bytes (1 switches on core 0)
Not Found: /
[pid: 28358|app: 0|req: 9/9] 180.241.97.91 () {32 vars in 464 bytes} [Sun May 31 03:27:36 2020] GET / => generated 2550 bytes in 3 msecs (HTTP/1.1 404) 4 headers in 129 bytes (2 switches on core 0)
Sun May 31 03:29:11 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 11:29:12 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x55b3eaa54cd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55b3eaa54cd0 pid: 28369 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28369)
spawned uWSGI worker 1 (pid: 28370, cores: 1)
Internal Server Error: /lottery
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/utils/deprecation.py", line 93, in __call__
    response = self.process_request(request)
  File "/root/miniconda3/lib/python3.7/site-packages/django/middleware/common.py", line 53, in process_request
    if self.should_redirect_with_slash(request):
  File "/root/miniconda3/lib/python3.7/site-packages/django/middleware/common.py", line 71, in should_redirect_with_slash
    not is_valid_path(request.path_info, urlconf) and
  File "/root/miniconda3/lib/python3.7/site-packages/django/urls/base.py", line 154, in is_valid_path
    resolve(path, urlconf)
  File "/root/miniconda3/lib/python3.7/site-packages/django/urls/base.py", line 25, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/root/miniconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 544, in resolve
    for pattern in self.url_patterns:
  File "/root/miniconda3/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/miniconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/root/miniconda3/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/miniconda3/lib/python3.7/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/root/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./backend/urls.py", line 22, in <module>
    url('^', include('backendApi.urls')),
  File "/root/miniconda3/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/root/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./backendApi/urls.py", line 2, in <module>
    from . import views
  File "./backendApi/views.py", line 121
    'Grade' : x[2]
          ^
SyntaxError: invalid syntax
[pid: 28370|app: 0|req: 1/1] 122.238.122.231 () {44 vars in 854 bytes} [Sun May 31 03:29:13 2020] GET /lottery => generated 153462 bytes in 72 msecs (HTTP/1.1 500) 2 headers in 96 bytes (2 switches on core 0)
Sun May 31 03:29:27 2020 - uWSGI worker 1 screams: UAAAAAAH my master disconnected: i will kill myself !!!
*** Starting uWSGI 2.0.18 (64bit) on [Sun May 31 11:29:28 2020] ***
compiled with version: 7.3.0 on 22 July 2019 16:51:41
os: Linux-4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019
nodename: Quasrain
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 1
current working directory: /root/HIT-100th-Anniversary-Celebration/backend
detected binary path: /root/miniconda3/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to .
your processes number limit is 7798
your memory page size is 4096 bytes
detected max file descriptor number: 65535
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address ./backend.sock fd 3
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
Python main interpreter initialized at 0x556ea2edccd0
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x556ea2edccd0 pid: 28374 (default app)
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 28374)
spawned uWSGI worker 1 (pid: 28375, cores: 1)
[pid: 28375|app: 0|req: 1/1] 122.238.122.231 () {44 vars in 854 bytes} [Sun May 31 03:29:29 2020] GET /lottery => generated 780 bytes in 115 msecs (HTTP/1.1 200) 4 headers in 128 bytes (1 switches on core 0)
